name: Demo CI/CD


on:
push:
branches: ["main"]


jobs:
demo-deploy:
runs-on: self-hosted


steps:
- name: Ambil kode terbaru
uses: actions/checkout@v3


- name: Simulasi install dependency
run: echo "Install dependency..."


- name: Membuat file otomatis
run: |
echo "Halo dari CI/CD" > surat.txt
echo "Dibuat pada $(date)" >> surat.txt


- name: Selesai
run: echo "Deployment Berhasil"
